//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdditionalUserInfo
{
    public string UserID { get; set; }
    public bool ShowEmail { get; set; }
    public bool ShowPhone { get; set; }
    public bool ShowBirthDate { get; set; }
    public byte[] DisplayPic { get; set; }
    public string GaduGadu { get; set; }
    public string Phone { get; set; }

    public virtual Users Users { get; set; }
}

public partial class BudgetPositions
{
    public long PositionID { get; set; }
    public int BudgetID { get; set; }
    public int ExpenseCatID { get; set; }
    public int ShopID { get; set; }
    public long ProdID { get; set; }
    public decimal Price { get; set; }
    public Nullable<System.DateTime> PurchaseDate { get; set; }
    public short Quantity { get; set; }
    public System.DateTime CreationDate { get; set; }
    public string AdditionalInfo { get; set; }

    public virtual Budgets Budgets { get; set; }
    public virtual ExpenseCategories ExpenseCategories { get; set; }
    public virtual Products Products { get; set; }
    public virtual Shops Shops { get; set; }
}

public partial class Budgets
{
    public Budgets()
    {
        this.BudgetPositions = new HashSet<BudgetPositions>();
    }

    public int BudgetID { get; set; }
    public string UserID { get; set; }
    public System.DateTime CreationDate { get; set; }
    public decimal Income { get; set; }
    public decimal Expenses { get; set; }

    public virtual ICollection<BudgetPositions> BudgetPositions { get; set; }
    public virtual Users Users { get; set; }
}

public partial class Categories
{
    public Categories()
    {
        this.Products = new HashSet<Products>();
    }

    public short Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Products> Products { get; set; }
}

public partial class Contacts
{
    public string UserID { get; set; }
    public string ContactID { get; set; }
    public System.DateTime CreationDate { get; set; }

    public virtual Users Users { get; set; }
}

public partial class Conversations
{
    public Conversations()
    {
        this.Messages = new HashSet<Messages>();
        this.Users1 = new HashSet<Users>();
    }

    public int Id { get; set; }
    public string CreationUserID { get; set; }
    public string Name { get; set; }
    public System.DateTime CreationDate { get; set; }

    public virtual Users Users { get; set; }
    public virtual ICollection<Messages> Messages { get; set; }
    public virtual ICollection<Users> Users1 { get; set; }
}

public partial class ExpenseCategories
{
    public ExpenseCategories()
    {
        this.BudgetPositions = new HashSet<BudgetPositions>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Amount { get; set; }
    public Nullable<decimal> Balance { get; set; }

    public virtual ICollection<BudgetPositions> BudgetPositions { get; set; }
}

public partial class Messages
{
    public int MessageID { get; set; }
    public int ConversationID { get; set; }
    public string SenderID { get; set; }
    public string Content { get; set; }
    public System.DateTime SendDate { get; set; }

    public virtual Conversations Conversations { get; set; }
    public virtual Users Users { get; set; }
}

public partial class Products
{
    public Products()
    {
        this.BudgetPositions = new HashSet<BudgetPositions>();
    }

    public long Id { get; set; }
    public short CategoryID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<BudgetPositions> BudgetPositions { get; set; }
    public virtual Categories Categories { get; set; }
}

public partial class Shops
{
    public Shops()
    {
        this.BudgetPositions = new HashSet<BudgetPositions>();
    }

    public int Id { get; set; }
    public string FriendlyName { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public string PostCode { get; set; }

    public virtual ICollection<BudgetPositions> BudgetPositions { get; set; }
}

public partial class Users
{
    public Users()
    {
        this.Budgets = new HashSet<Budgets>();
        this.Contacts = new HashSet<Contacts>();
        this.Conversations = new HashSet<Conversations>();
        this.Messages = new HashSet<Messages>();
        this.Conversations1 = new HashSet<Conversations>();
    }

    public string UserName { get; set; }
    public string Passwd { get; set; }
    public string Email { get; set; }
    public System.DateTime BirthDate { get; set; }
    public System.DateTime RegisterDate { get; set; }
    public string VerifCode { get; set; }

    public virtual AdditionalUserInfo AdditionalUserInfo { get; set; }
    public virtual ICollection<Budgets> Budgets { get; set; }
    public virtual ICollection<Contacts> Contacts { get; set; }
    public virtual ICollection<Conversations> Conversations { get; set; }
    public virtual ICollection<Messages> Messages { get; set; }
    public virtual ICollection<Conversations> Conversations1 { get; set; }
}
