//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CheaperEntities : DbContext
{
    public CheaperEntities()
        : base("name=CheaperEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<AdditionalUserInfo> AdditionalUserInfo { get; set; }
    public DbSet<BudgetPositions> BudgetPositions { get; set; }
    public DbSet<Budgets> Budgets { get; set; }
    public DbSet<Categories> Categories { get; set; }
    public DbSet<Contacts> Contacts { get; set; }
    public DbSet<Conversations> Conversations { get; set; }
    public DbSet<ExpenseCategories> ExpenseCategories { get; set; }
    public DbSet<Messages> Messages { get; set; }
    public DbSet<Products> Products { get; set; }
    public DbSet<Shops> Shops { get; set; }
    public DbSet<Users> Users { get; set; }
}
